<a href="https://colab.research.google.com/github/Rao-Kai/dl_pytorch/blob/main/chapter2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
x = torch.arange(4).reshape(2,2)
x.shape

torch.Size([2, 2])

In [ ]:
x=torch.arange(24).reshape(2,3,4)
a=2
x**a

tensor([[[  0,   1,   4,   9],
         [ 16,  25,  36,  49],
         [ 64,  81, 100, 121]],

        [[144, 169, 196, 225],
         [256, 289, 324, 361],
         [400, 441, 484, 529]]])

In [ ]:
x=torch.arange(4).reshape(2,2)
x.sum(axis=0)

tensor([2, 4])

In [ ]:
x=torch.tensor([1,2,3,4], dtype=torch.float32)
y=torch.ones(4, dtype=torch.float32)
z=torch.dot(x,y)  
# dot用于向量相乘
z

tensor(10.)

In [10]:
A = torch.arange(20, dtype = torch.float32).reshape(5,4)
z = torch.mv(A, y)
# mv表示矩阵和向量相乘 matrix * vector
A, y, z

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([1., 1., 1., 1.]),
 tensor([ 6., 22., 38., 54., 70.]))

In [14]:
B = torch.arange(16, dtype = torch.float32).reshape(4,4)
z = torch.mm(A, B)
z

tensor([[ 56.,  62.,  68.,  74.],
        [152., 174., 196., 218.],
        [248., 286., 324., 362.],
        [344., 398., 452., 506.],
        [440., 510., 580., 650.]])

In [16]:
z = torch.norm(x)
z

tensor(5.4772)