In [15]:
import numpy as np
import torch
from torch.utils import data
from d2l import torch as d2l
from torch import nn

In [16]:
true_w = torch.tensor([2, -3.4])
true_b = 4.2
features, labels = d2l.synthetic_data(true_w, true_b, 1000)

In [17]:
def load_array(data_arrays, batch_size, is_train = True):
    dataset = data.TensorDataset(*data_arrays)
    return data.DataLoader(dataset, batch_size, shuffle=is_train)

In [18]:
batch_size = 10
data_iter = load_array((features, labels), batch_size)

In [19]:
next(iter(data_iter))

[tensor([[-7.1918e-01,  1.4541e+00],
         [-4.3751e-01,  7.5707e-02],
         [ 1.8059e+00, -2.3621e-01],
         [-3.8955e-01,  4.0950e-04],
         [ 1.5181e+00, -5.6703e-01],
         [-4.9628e-01,  5.5227e-01],
         [-2.1622e-01, -6.3930e-01],
         [ 2.3845e+00,  6.6537e-01],
         [ 8.8322e-01,  2.6399e-01],
         [ 5.8099e-01,  6.9272e-01]]),
 tensor([[-2.1897],
         [ 3.0766],
         [ 8.6126],
         [ 3.4195],
         [ 9.1672],
         [ 1.3512],
         [ 5.9475],
         [ 6.7088],
         [ 5.0533],
         [ 3.0142]])]

In [20]:
# nn.Linear中，第一个是输入的神经元个数，第二个是输出神经元个数
# https://blog.csdn.net/zhaohongfei_358/article/details/122797190
net = nn.Sequential(nn.Linear(2, 1))

In [21]:
# 初始化nn的参数
net[0].weight.data.normal_(0, 0.01)
net[0].bias.data.fill_(0)

tensor([0.])

In [22]:
# 定义loss
loss = nn.MSELoss()

In [23]:
# 定义优化算法
trainer = torch.optim.SGD(net.parameters(), lr=0.03)

In [24]:
num_epochs = 3
for epoch in range(num_epochs):
    for X, y in data_iter:
        l = loss(net(X) ,y)
        trainer.zero_grad()
        l.backward()
        trainer.step()
    l = loss(net(features), labels)
    print(f'epoch {epoch + 1}, loss {l:f}')

epoch 1, loss 0.000245
epoch 2, loss 0.000102
epoch 3, loss 0.000102


In [25]:
w = net[0].weight.data
print(w)
print(w.reshape(true_w.shape))
print('w的估计误差：', true_w - w.reshape(true_w.shape))
b = net[0].bias.data
print(b)
print('b的估计误差：', true_b - b)

tensor([[ 2.0000, -3.4004]])
tensor([ 2.0000, -3.4004])
w的估计误差： tensor([1.0729e-05, 3.7909e-04])
tensor([4.2002])
b的估计误差： tensor([-0.0002])


In [26]:
x=torch.tensor([ 1.9989, -3.4005])
x.shape

torch.Size([2])

In [27]:
# 只有一个中括号就当列向量看，有两个中括号当矩阵看
x=torch.tensor([[ 1.9989, -3.4005]])
x.shape

torch.Size([1, 2])

In [28]:
# b会自动加到x的每一行，前提是列数对上,如果b只给1的话，那么x所有元素都加1
x=torch.tensor([[ 0.4162, -1.5868],
         [-0.4829,  0.1374],
         [-0.5748, -0.6860],
         [-0.6347,  0.1200],
         [-0.9963,  2.0180],
         [ 1.5813, -1.2615],
         [-0.4949,  2.0363],
         [ 0.3605,  0.5714],
         [ 0.4059, -1.2410],
         [ 0.1744,  1.4118]])
b = torch.tensor([[1, 2]])
# b = torch.tensor([1])
z = x + b
x.shape, z

(torch.Size([10, 2]),
 tensor([[1.4162e+00, 4.1320e-01],
         [5.1710e-01, 2.1374e+00],
         [4.2520e-01, 1.3140e+00],
         [3.6530e-01, 2.1200e+00],
         [3.7000e-03, 4.0180e+00],
         [2.5813e+00, 7.3850e-01],
         [5.0510e-01, 4.0363e+00],
         [1.3605e+00, 2.5714e+00],
         [1.4059e+00, 7.5900e-01],
         [1.1744e+00, 3.4118e+00]]))

In [32]:
# 在pytorch框架下，如果只给一个参数，比如torch.zeros(10)，那返回的就是张量，
# 这个东西既不是行向量也不是列向量，因为转置是不会改变这个东西的
# 所以，当需要一个列向量的时候，应该给两个参数，比如torch.zeros(10,1)
# 所以当给一个参数的时候，理解成行向量就ok
# 当对这种类向量进行探究的时候，即n*1或1*n的矩阵，两个框就是矩阵，shape返回两个数字；一个框就是张量，shape返回只有一个数
aa=torch.tensor([[ 2.3426],
         [ 2.6211],
         [-1.2698],
         [ 9.9087],
         [-0.2319],
         [ 5.0248],
         [ 8.5821],
         [ 7.5928],
         [ 3.2568],
         [ 6.8076]])
aa.shape
b=aa.T
b, b.shape
aa = torch.zeros(10,1)
aa

tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]])