In [1]:
import numpy as np
import torch
from torch.utils import data
from d2l import torch as d2l
from torch import nn

In [2]:
true_w = torch.tensor([2, -3.4])
true_b = 4.2
features, labels = d2l.synthetic_data(true_w, true_b, 1000)

In [3]:
def load_array(data_arrays, batch_size, is_train = True):
    dataset = data.TensorDataset(*data_arrays)
    return data.DataLoader(dataset, batch_size, shuffle=is_train)

In [4]:
batch_size = 10
data_iter = load_array((features, labels), batch_size)

In [5]:
next(iter(data_iter))

[tensor([[ 0.0334,  1.5688],
         [ 0.1221, -0.4503],
         [-0.2772,  2.1081],
         [ 0.5338, -1.9988],
         [ 1.2632,  1.5276],
         [ 0.0343, -0.2446],
         [ 0.2368,  1.1869],
         [-1.3307, -0.9556],
         [-0.9820, -0.8594],
         [ 0.9157,  1.9896]]),
 tensor([[-1.0528],
         [ 5.9643],
         [-3.5213],
         [12.0687],
         [ 1.5284],
         [ 5.0932],
         [ 0.6406],
         [ 4.7760],
         [ 5.1744],
         [-0.7360]])]

In [6]:
# nn.Linear中，第一个是输入的神经元个数，第二个是输出神经元个数
# https://blog.csdn.net/zhaohongfei_358/article/details/122797190
net = nn.Sequential(nn.Linear(2, 1))

In [7]:
# 初始化nn的参数
net[0].weight.data.normal_(0, 0.01)
net[0].bias.data.fill_(0)

tensor([0.])

In [8]:
# 定义loss
loss = nn.MSELoss()

In [9]:
# 定义优化算法
trainer = torch.optim.SGD(net.parameters(), lr=0.03)

In [10]:
num_epochs = 3
for epoch in range(num_epochs):
    for X, y in data_iter:
        l = loss(net(X) ,y)
        trainer.zero_grad()
        l.backward()
        trainer.step()
    l = loss(net(features), labels)
    print(f'epoch {epoch + 1}, loss {l:f}')

epoch 1, loss 0.000225
epoch 2, loss 0.000090
epoch 3, loss 0.000091


In [11]:
w = net[0].weight.data
print(w.reshape(true_w.shape))
print('w的估计误差：', true_w - w.reshape(true_w.shape))
b = net[0].bias.data
print(b)
print('b的估计误差：', true_b - b)

tensor([ 2.0001, -3.3999])
w的估计误差： tensor([-1.0085e-04, -6.8188e-05])
tensor([4.1989])
b的估计误差： tensor([0.0011])


In [12]:
x=torch.tensor([ 1.9989, -3.4005])
x.shape

torch.Size([2])

In [13]:
x=torch.tensor([[ 1.9989, -3.4005]])
x.shape

torch.Size([1, 2])